### ISSUE TITLE
;Icons are darker than without this addon

### ISSUE THREAD

**Issue by Sythr4l** [emallson/HideActionBarBorders#2]
Using this addon makes the icons darker than without.  Is there an additional filter being applied to the icon images?

**Comment by emallson** [comment]
It replaces the overlay textures with another but not one that i've noticed being darker. Can you screenshot before/after?

**Comment by Sythr4l** [comment]
You bet! I should have included this to begin with.  Left is without and right is with the addon enabled. 
![HideActionBarBorder difference](https://user-images.githubusercontent.com/113131440/214107551-d64eb101-8d5b-4c36-82e9-70f12e5596f1.png)

**Comment by Sythr4l** [comment]
It seems to change with a reload of the UI.  Some of the icons go back to being brighter but others are still darker.  It's not consistent though, as I did another reload and the icons that were brighter turned darker again.

**Comment by emallson** [comment]
I suspect it is a texture stacking incorrectly. I'll look into it. Thanks for the report :+1:

**Comment by Sythr4l** [comment]
Any update on this issue? it's still happening for me :(

**Comment by emallson** [comment]
Not yet but I have to redo the texture files for 10.1 because of UI changes so I'll be working on it for the patch

**Comment by emallson** [comment]
This should be fixed in version 1.2 which is going up on Curseforge now and should be available shortly.

**Comment by Sythr4l** [comment]
Unfortunately this is still happening for me with the latest version.
![Untitled](https://github.com/emallson/HideActionBarBorders/assets/113131440/c31923a3-9383-43a1-8d00-bf83dd64d823)

**Comment by emallson** [comment]
@Sythr4l you'll be happy to know that I finally figured out how to reproduce this reliably! Switching between characters always triggered it after a few swaps, so I was able to debug and fix the underlying issue. That fix is now going up as part of v1.2.2
